# FROM ubuntu

# RUN apt-get update -y && apt-get install --no-install-recommends -y -q curl python build-essential git ca-certificates
# RUN mkdir /nodejs && curl http://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x64.tar.gz | tar xvzf - -C /nodejs --strip-components=1

# ENV PATH $PATH:/nodejs/bin

 FROM readytalk/nodejs

# Fix upstart
# RUN rm -rf /sbin/initctl && ln -s /sbin/initctl.distrib /sbin/initctl

  WORKDIR /app
  ADD package.json /app/
  RUN npm install
#  RUN npm install forever -g
  ADD serverInterop.js /app
#  ADD serverInterop.conf /etc/init
#  ADD serverInterop /etc/init.d
#  CMD serverInterop start
   CMD env DATABASE_URL="postgres://interop:mdp@interop-postgres:5432/interop" LOGINURL="http://interop.etalab.gouv.fr/#!/login" API_KEY="myapikey" PORT="8080" API_USERNAME="myuser" DISCOURSE_GROUP="interop-messagerie" node serverInterop.js
