# FROM ubuntu

# RUN apt-get update -y && apt-get install --no-install-recommends -y -q curl python build-essential git ca-certificates
# RUN mkdir /nodejs && curl http://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x64.tar.gz | tar xvzf - -C /nodejs --strip-components=1

# ENV PATH $PATH:/nodejs/bin

 FROM readytalk/nodejs

# Fix upstart
# RUN rm -rf /sbin/initctl && ln -s /sbin/initctl.distrib /sbin/initctl

  WORKDIR /app
  ADD package.json /app/
  RUN npm install
#  RUN npm install forever -g
  ADD serverInterop.js /app
#  ADD serverInterop.conf /etc/init
#  ADD serverInterop /etc/init.d
#  CMD serverInterop start
  CMD echo "This is a test."
   CMD env DATABASE_URL="postgres://interop:fanfaron@interop-postgres:5432/interop" LOGINURL="http://84.39.48.2184.39.48.2184.39.48.2184.39.48.2184.39.48.2184.39.48.2184.39.48.2184.39.48.21/interop/appv2/#!/login" API_KEY="b0e562e8d5c733e66bfece696b5b8e40ac83dd9b61491470c7c448eccbe676a9" API_USERNAME="jploquin" DISCOURSE_GROUP="interop-messagerie" node serverInterop.js
#   CMD env DATABASE_URL="postgres://interop:fanfaron@interop-postgres:5432/interop" forever start serverInterop.js
#  CMD []
#  ENTRYPOINT ["/nodejs/bin/npm", "start"]
